services:
  redis:
    image: "redis:7"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - common-network
    command: redis-server --save 60 1 --loglevel warning 
    ports:
      - "6379:6379"

volumes:
  redis_data:

networks:
  common-network:
    driver: bridge